config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"
  resources :products do
    resources :purchases, only: [:index, :create]
    resources :comments, only: :create
  end
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :product_category
  belongs_to :product_condition
  belongs_to :shipping_burden
  belongs_to :shipping_area
  belongs_to :days_to_ship

  belongs_to :user
  has_one :purchase
  has_one_attached :image

  has_many :comments

  validates :product_name, presence: true
  validates :product_discription, presence: true
  validates :product_category_id, presence: true
  validates :product_condition_id, presence: true
  validates :shipping_burden_id, presence: true
  validates :shipping_area_id, presence: true
  validates :days_to_ship_id, presence: true
  validates :purchase_price, presence: true
  validates_inclusion_of :purchase_price, in: 300..99_999_999

  validates :image, presence: true

  validates :product_category_id, numericality: { other_than: 1, message: 'is not included in the list' }
  validates :product_condition_id, numericality: { other_than: 1, message: 'is not included in the list' }
  validates :shipping_burden_id, numericality: { other_than: 1, message: 'is not included in the list' }
  validates :shipping_area_id, numericality: { other_than: 1, message: 'is not included in the list' }
  validates :days_to_ship_id, numericality: { other_than: 1, message: 'is not included in the list' }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  before_action :move_to_index, except: [:index, :show, :new, :create]
  before_action :move_to_index_three, only: [:edit]
  before_action :set_product_two, only: [:show]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to product_path
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(:product_name, :product_discription, :product_category_id, :product_condition_id,
                                    :shipping_burden_id, :shipping_area_id, :days_to_ship_id, :image, :purchase_price)
          .merge(user_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_product_two
    @comments = @product.comments.includes(:user)
    @comment = Comment.new
  end
  
  def move_to_index
    redirect_to action: :index unless current_user.id == @product.user_id
  end

  def move_to_index_three
    redirect_to root_path if @product.purchase.present? && user_signed_in? && (current_user.id == @product.user_id)
  end
end

app/views/products/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('juken-logo-black.png' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">受験校の情報を入力</h2>
    <%= form_with model:@product,local: true do |f| %>
    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
        <%= render 'shared/error_messages', model: @product %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%# 受験校画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        受験校画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /受験校画像 %>

    <%# 受験校と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        受験校
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :product_name, class:"items-text", id:"item-name", placeholder:"受験校（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          受験校の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :product_discription, class:"items-text", id:"item-info", placeholder:"受験校の説明（必須 1,000文字まで）（出願締切日、一次試験日、一次合格発表日、二次試験日、二次試験合格発表日、手続締切日など）例）出：1/7、①1/19、❶1/23、②1/27ー1/29（選択）、❷2/5、手2/11、1次：TKP新大阪駅カンファレンスセンター、2次：東京赤坂CP）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /受験校と商品説明 %>

    <%# 受験の難易度 %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>受験の難易度</span>
        <a class="question" href="https://xn--0kq33cz5c8wmwrqqw1d.com/?p=202">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          受験区分
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:product_category_id, ProductCategory.all,  :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          偏差値
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:product_condition_id, ProductCondition.all,  :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
        <div class="weight-bold-text">
          共通テストボーダー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_burden_id, ShippingBurden.all,  :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
      </div>
    </div>
    <%# /受験の難易度 %>

    <%# 受験会場 %>
    <div class="items-detail">
      <div class="weight-bold-text">受験会場</div>
      <div class="form">
        <div class="weight-bold-text">
          試験場の場所
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_area_id, ShippingArea.all,  :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
      </div>
    </div>
    <%# /受験会場 %>
    <%# 受験会場 %>
    <div class="items-detail">
      <div class="weight-bold-text">現状</div>
      <div class="form">
         <div class="weight-bold-text">
          受験の状況
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:days_to_ship_id, DaysToShip.all,  :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /受験会場 %>

    <%# 学納金 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>学納金等 総計<br>(¥3,500k〜45,500k)</span>
        <a class="question" href="https://xn--0kq33cz5c8wmwrqqw1d.com/?p=214">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>金額</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :purchase_price, class:"price-input", id:"item-price", placeholder:"例）300" %>k
        </div>
        <%# <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div> %>
      </div>
    </div>
    <%# /学納金等 総計 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">推奨されている受験校（◯）、</a>
        <a href="#">受験可の受験校（△）</a>
        を必ず確認すること。
      </p>
      <p class="sentence">
        また2次試験が複数日選択可能な場合は記載すること。
        <a href="#">小論文の試験</a>
        が一次試験で実施される可能性がある。
      </p>
      <p class="sentence">
        また、情報入力をもって
        <a href="#">受験することに</a>
        同意したこととする。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "修正する" ,class:"sell-btn" %>
      <%=link_to 'もどる', "#", class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">JUKEN利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('juken-logo-black.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Juken,Inc.
    </p>
  </footer>
</div>

app/views/products/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      人生を大逆転させる大学受験
    </h2>
    <p class='service-explain'>
      苦難を乗り切り合格すれば明るい未来が拓ける
    </p>
    <p class='service-explain'>
      最後まで悔いを残すことなくやりきれ！
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      今やらなきゃ損な3つの理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "juken-intro01.png", class:"list-pict" %>
        <%# <span class='reason-list-number'>壱</span> %>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>時間</span>
          自由自在
        </h3>
        <p class='reason-list-description'>
          楽しい大学生活が待っている！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "juken-intro02.png", class:"list-pict" %>
        <%# <span class='reason-list-number'>弐</span> %>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>お金</span>
          将来安泰
        </h3>
        <p class='reason-list-description'>
          安定した収入と社会的ステータス
        </p>
      </li>
      <li class='list'>
        <%= image_tag "juken-intro03.png", class:"list-pict" %>
        <%# <span class='reason-list-number'>参</span> %>
        <h3 class='reason-list-text'>
        <span class='reason-list-blue-text'>夢</span>
          理想の自分
        </h3>
        <p class='reason-list-description'>
          なりたい自分になれる
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      人生最大のチャンスを逃すな！
    </h2>
    <p class='ad-explain'>
      伸びしろは無限大。やればばるだけ合格に近づく
    </p>
    <p class='ad-explain'>
      塾長・講師陣・お父さん・お母さんの最大級のバックアップ体制
    </p>
    <p class='ad-explain'>
      豊富な受験校に多数の受験機会
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      合格のための3か条
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "juken-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          解き方の徹底
        </h3>
        <p class='feature-list-description'>
          時間配分・いい点を取ろうとしない・検算の徹底
        </p>
      </li>
      <li class='list'>
        <%= image_tag "juken-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          基礎の徹底
        </h3>
        <p class='feature-list-description'>
          今までやってきた問題集を信じて繰り返す
        </p>
      </li>
      <li class='list'>
        <%= image_tag "juken-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          絶対に諦めるな
        </h3>
        <p class='feature-list-description'>
          5点で合格もある。目標点数・得点率を決めるな
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>受験校</h2>
    <div class="subtitle" >
      この中からどこを選ぶ？
    </div>
    <ul class='item-lists'>
      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <% @products.each do |product| %>

      <li class='list'>

        <%= link_to "#" do %>

        <div class='item-img-content'>
          <%= link_to image_tag(product.image, class: "item-img" ), product_path(product.id), method: :get  %>
          <%# 商品が売れていればpassedを表示しましょう %>
          <%# <% if product.purchase.present? %>
          <% if product.days_to_ship_id == 2 %>
            <div class='sold-out'>
              <span>Passed </span>
            </div>
          <% end %>
          <%# //商品が売れていればpassedを表示しましょう %>

        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= product.product_name %>
          </h3>
          <div class='item-price'>
            <%# <span><%= product.purchase_price 円 #一覧に受験区分を追加＃%>
            <span><%= product.product_category.name %>
            <br>
            <%# <%= product.shipping_burden.name ＃一覧に偏差値を記載＃%>
            <%= product.days_to_ship.name %>
            
            </span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <%# //商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <%# 商品がない場合は以下のダミー商品が表示されるようにしましょう %>
      <%# 商品がある場合は表示されないようにしましょう %>
      <li class='list'>

      <% if @products.length == 0 %>

        <%= link_to '#' do %>
        <%= image_tag "icon-univ.png", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            受験したい学校をお父さんに言ってください
          </h3>
          <div class='item-price'>
            <span>一般/共通テスト利用 前期/中期/後期 1次/2次<br>現在の状況</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>

      <% end %>

      </li>
      <%# //商品がある場合は表示されないようにしましょう %><%# //商品がない場合は以下のダミー商品が表示されるようにしましょう %>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
<%= link_to('/products/new', class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>受験校追加</span>
  <%= image_tag 'icon-univ.png' , size: '185x75' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/products/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('juken-logo-black.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">受験校の情報を入力</h2>
    <%= form_with model:@product, local: true do |f| %>

    <%= render 'shared/error_messages', model: @product %>

    <%# 受験校画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        受験校画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /受験校画像 %>
    <%# 受験校と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        受験校
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :product_name, class:"items-text", id:"item-name", placeholder:"受験校（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          受験校の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :product_discription, class:"items-text", id:"item-info", placeholder:"受験校の説明（必須 1,000文字まで）（出願締切日、一次試験日、一次合格発表日、二次試験日、二次試験合格発表日、手続締切日など）例）出：1/7、①1/19、❶1/23、②1/27ー1/29（選択）、❷2/5、手2/11、1次：TKP新大阪駅カンファレンスセンター、2次：東京赤坂CP）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /受験校と商品説明 %>




    <%# 受験の難易度 %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>受験の難易度</span>
        <a class="question" href="https://xn--0kq33cz5c8wmwrqqw1d.com/?p=202">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          受験区分
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:product_category_id, ProductCategory.all,  :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          偏差値
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:product_condition_id, ProductCondition.all,  :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
         <div class="weight-bold-text">
          共通テストボーダー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_burden_id, ShippingBurden.all,  :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
     </div>
    </div>
    <%# /受験の難易度 %>

    <%# 受験会場 %>
    <div class="items-detail">
         <div class="weight-bold-text">受験会場</div>
      <div class="form">
        <div class="weight-bold-text">
          試験場の場所
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_area_id, ShippingArea.all,  :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
       </div>
    </div>
    <%# /受験会場 %>
        <%# 受験会場 %>
    <div class="items-detail">
         <div class="weight-bold-text">現状</div>
      <div class="form">
         <div class="weight-bold-text">
          受験の状況
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:days_to_ship_id, DaysToShip.all,  :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /受験会場 %>

    <%# 学納金等 総計 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>学納金等 総計<br>(¥3,500k〜45,500k)</span>
        <a class="question" href="https://xn--0kq33cz5c8wmwrqqw1d.com/?p=214">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>金額</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :purchase_price, class:"price-input", id:"item-price", placeholder:"例）300" %>k
        </div>
        <%# <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span> %>
      </div>
    </div>
    <%# /学納金等 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">推奨されている受験校（◯）、</a>
        <a href="#">受験可の受験校（△）</a>
        を必ず確認すること。
      </p>
      <p class="sentence">
        また2次試験が複数日選択可能な場合は記載すること。
        <a href="#">小論文の試験</a>
        が一次試験で実施される可能性がある。
      </p>
     <p class="sentence">
        また、情報入力をもって
        <a href="#">受験することに</a>
        同意したこととする。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "受験する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">JUKEN利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('juken-logo-black.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Juken,Inc.
    </p>
  </footer>
</div>

app/views/products/show.html.erb
<%= render "shared/header" %>

<%# 受験校の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @product.product_name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @product.image, class:"item-box-img" %>
      <%# 商品が売れている場合は、passedを表示しましょう %>
      <%# <% if product.purchase.present? %>
      <% if @product.days_to_ship_id == 2 %>
          <div class="sold-out">
            <span>Passed</span>
          </div>
        <% end %>
      <%# //商品が売れている場合は、passedを表示しましょう %>

    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%# ¥ <%= @product.purchase_price %>
        <%= @product.product_category.name %>
      </span>
      <%# <span class="item-postage"> %>
        <%# <%= @product.shipping_burden.name  %>
        <%# 偏差値  <%= @product.product_condition.name %>
      <%# </span>  %>
    </div>
    <%# ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>
    <% if user_signed_in? && (current_user.id == @product.user_id && !@product.purchase.present?)   %>

    <%= link_to "受験校情報の編集", edit_product_path, method: :get, class: "item-red-btn" %>
    <p class="or-text">or</p>
    <%# <%= link_to "削除", product_path, method: :delete, class:"item-destroy" %> #誤って削除しないように一旦、マスク#

    <%# <% elsif user_signed_in? && (current_user.id != @product.user_id)   % %>
    <%# 商品が売れていない場合はこちらを表示しましょう ＃購入ページへのシフトを回避＃%>
      <%# <% if !@product.purchase.present? % %>
        <%# <%= link_to "合格確定", product_purchases_path(@product.id), class:"item-red-btn"% %>
      <%# <% end  %>
    <%# //商品が売れていない場合はこちらを表示しましょう ＃購入ページへのシフトを回避＃%>
    <% end %>
    <%# //ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>

    <div class="item-explain-box">
      <span>
        <%= @product.product_discription %>
      </span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">受験区分</th>
          <td class="detail-value">
          <%= @product.product_category.name %>
          </td>
        </tr>
        <tr>
          <th class="detail-item">学納金 総計</th>
          <td class="detail-value">
          ¥<%= @product.purchase_price %>k
          </td>
        </tr>
        <tr>
          <th class="detail-item">偏差値</th>
          <td class="detail-value">
          <%= @product.product_condition.name %>
          </td>
        </tr>
        <tr>
          <th class="detail-item">共通テストボーダー</th>
          <td class="detail-value">
          <%= @product.shipping_burden.name %>
          </td>
        </tr>
        <tr>
          <th class="detail-item">試験場の場所</th>
          <td class="detail-value">
          <%= @product.shipping_area.name %>
          </td>
        </tr>
        <tr>
          <th class="detail-item">受験の状況</th>
          <td class="detail-value">
          <%= @product.days_to_ship.name %>
          </td>
        </tr>
        <tr>
          <th class="detail-item">情報収集・提供</th>
          <td class="detail-value">
          <%= @product.user.nickname %>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>誤った記載の通報</span>
      </div>
    </div>
  </div>
  <%# /受験校の概要 %>

  <%# コメント表示 %>
  <div id="comments">
  <h4>＜コメント一覧＞</h4>
    <% @product.comments.each do |comment| %>
      <div class="comment">
        <p class="user-info"><%= comment.user.nickname %>： </p>
        <p><%= comment.text%></p>
      </div>
    <% end %>
  </div>
  <%# /コメント表示 %>
  
<%# 新コメント追加 %>
<%# <div class="comment-form"> %>
<div class="comment-box">
  <% if user_signed_in? %>
    <%= form_with model: [@product, @comment], id: "comment-form" do |f| %>
      <%= f.text_area :text , class: "comment-text"%>
      <%# <%= f.submit "コメントをする", class: "comment-submit" % %>
      <p class="comment-warn">
        <%# 相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。 %>
       悠さんのことを考え精神的に負担にならないコメントを心がけよう。
        <br>
        もう十分に頑張っています
        <br>
        安心して試験に臨めるといいね。
       </p>
      <%= f.submit "コメントをする", class: "comment-btn" %>
    <% end %>
  <% end %>
</div>
<%# /新コメント追加 %>

  <%# コメントのための最初の部分  %>
  <%# <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        悠さんのことを考え精神的に負担にならないコメントを心がけよう。
        <br>
        もう十分に頑張っています
        <br>
        安心して試験に臨めるといいね。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <%# <span>コメントする<span>
      </button>
    </form>
  </div> % %>
<%# /コメントのための最初の部分 %>

  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の受験校
    </a>
    <a href="#" class="change-item-btn">
      後ろの受験校 ＞
    </a>
  </div>
  <a href="#" class="another-item">
  <%= @product.product_category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>